// Generate Zod schemas from the committed JSON Schema files.
//
//     node packages/contracts/scripts/gen-zod.mjs
//
// Run AFTER scripts/gen.py. Output lands in src/generated/ and is committed; the drift
// guard (`pnpm run check`) regenerates and fails on any diff.
//
// Both the emitter and the output must be deterministic — a nondeterministic generator
// turns the drift guard into a random failure that people learn to ignore.

import { readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { jsonSchemaToZod } from "json-schema-to-zod";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SCHEMA_DIR = join(ROOT, "schema");
const OUT_DIR = join(ROOT, "src", "generated");

// ASCII only: this string lands in committed files that the drift guard byte-compares.
const HEADER = "// GENERATED by packages/contracts/scripts/gen-zod.mjs -- do not edit.\n";

/** action_call.schema.json -> ActionCall */
const pascal = (file) =>
  file
    .replace(/\.schema\.json$/, "")
    .split("_")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");

/** ActionCall -> actionCallSchema */
const schemaConst = (name) => `${name.charAt(0).toLowerCase()}${name.slice(1)}Schema`;

/**
 * Inline every `#/$defs/...` reference.
 *
 * The committed schema files keep `$defs` + `$ref` because that is canonical JSON Schema
 * and it keeps the artifact readable. The Zod emitter, however, renders an unresolved
 * `$ref` as `z.any()` — which would silently drop validation for nested Element and
 * Viewport objects and, worse, discard their `additionalProperties: false`. That is the
 * no-coordinates guarantee, so losing it on the TS side is a security regression, not a
 * cosmetic one. Resolve refs here, right before generation.
 */
function deref(node, defs, seen = []) {
  if (Array.isArray(node)) return node.map((child) => deref(child, defs, seen));
  if (node === null || typeof node !== "object") return node;

  if (typeof node.$ref === "string") {
    const match = /^#\/\$defs\/(.+)$/.exec(node.$ref);
    if (!match) throw new Error(`Unsupported $ref (only #/$defs/* is handled): ${node.$ref}`);
    const key = match[1];
    if (seen.includes(key)) {
      throw new Error(`Recursive $ref: ${[...seen, key].join(" -> ")}. Zod needs z.lazy() here.`);
    }
    const target = defs[key];
    if (!target) throw new Error(`Dangling $ref: ${node.$ref}`);
    // Sibling keys (e.g. a `default` alongside the $ref) win over the resolved target.
    const { $ref: _ignored, ...siblings } = node;
    return { ...deref(target, defs, [...seen, key]), ...siblings };
  }

  return Object.fromEntries(Object.entries(node).map(([k, v]) => [k, deref(v, defs, seen)]));
}

const files = (await readdir(SCHEMA_DIR)).filter((f) => f.endsWith(".schema.json")).sort();
if (files.length === 0) throw new Error(`No schemas in ${SCHEMA_DIR} — run scripts/gen.py first.`);

const exports = [];

for (const file of files) {
  const name = pascal(file);
  const constName = schemaConst(name);
  const { $defs = {}, $id: _id, ...root } = JSON.parse(await readFile(join(SCHEMA_DIR, file), "utf8"));
  const schema = deref(root, $defs);

  const body = jsonSchemaToZod(schema, { module: "esm", name: constName, type: name });

  await writeFile(join(OUT_DIR, `${file.replace(/\.schema\.json$/, "")}.ts`), HEADER + body, "utf8");
  exports.push({ module: file.replace(/\.schema\.json$/, ""), constName, name });
}

// A barrel so consumers import from one place and the generated surface stays explicit.
const barrel =
  HEADER +
  exports.map((e) => `export { ${e.constName}, type ${e.name} } from "./${e.module}.js";`).join("\n") +
  '\nexport { PROTOCOL_VERSION } from "./version.js";\n';

await writeFile(join(OUT_DIR, "index.ts"), barrel, "utf8");

console.log(`zod: ${exports.map((e) => e.constName).join(", ")}`);
