"""Emit JSON Schema from the Pydantic source of truth.

    uv run --project backend python packages/contracts/scripts/gen.py

Writes `schema/*.schema.json` and `src/generated/version.ts`. Both are COMMITTED, and
`pnpm run check` regenerates then fails on any diff — so a schema change that skips
regeneration cannot merge.

Output must be byte-stable across runs, or the drift guard cries wolf: hence sorted keys
and a fixed indent.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

from inbox_contracts import PROTOCOL_VERSION, WIRE_MODELS

ROOT = Path(__file__).resolve().parents[1]
SCHEMA_DIR = ROOT / "schema"
GENERATED_TS = ROOT / "src" / "generated"


def _snake(name: str) -> str:
    """ActionCall -> action_call"""
    return re.sub(r"(?<!^)(?=[A-Z])", "_", name).lower()


def _strip_prose(node: object) -> object:
    """Drop `description` keys recursively.

    Pydantic lifts class docstrings into the schema. That prose is the *source's*
    documentation; copying it into two generated artifacts guarantees it drifts from
    models.py, and it bloats every schema diff for a comment edit. The contract files
    carry structure only — read models.py for the why.
    """
    if isinstance(node, dict):
        return {k: _strip_prose(v) for k, v in node.items() if k != "description"}
    if isinstance(node, list):
        return [_strip_prose(v) for v in node]
    return node


def _fill_container_defaults(schema: dict) -> dict:
    """Make `default_factory` defaults explicit in the emitted schema.

    Pydantic does not serialize a `default_factory` into JSON Schema, so a field like
    `elements: list[Element] = Field(default_factory=list)` comes out neither `required`
    nor carrying a `default`. Generators read that as "optional", and the TS side ends up
    with `Element[] | undefined` for a field that is *always* a list in Python.

    Rather than let the two sides disagree, state the default the Python model actually
    has. Applies only to container types, where the empty value is unambiguous.
    """
    required = set(schema.get("required", []))
    empty_for: dict[str, object] = {"array": [], "object": {}}
    for name, prop in schema.get("properties", {}).items():
        if name in required or "default" in prop:
            continue
        if prop.get("type") in empty_for:
            prop["default"] = empty_for[prop["type"]]
    for definition in schema.get("$defs", {}).values():
        _fill_container_defaults(definition)
    return schema


def main() -> int:
    SCHEMA_DIR.mkdir(parents=True, exist_ok=True)
    GENERATED_TS.mkdir(parents=True, exist_ok=True)

    written: list[str] = []
    for model in WIRE_MODELS:
        schema = _fill_container_defaults(_strip_prose(model.model_json_schema(by_alias=True)))
        # A stable $id makes the emitted file self-describing and gives the Zod generator
        # a name to hang the export off.
        schema = {"$id": f"https://inbox-autopilot.dev/schema/{_snake(model.__name__)}.json", **schema}
        path = SCHEMA_DIR / f"{_snake(model.__name__)}.schema.json"
        path.write_text(json.dumps(schema, indent=2, sort_keys=True) + "\n", encoding="utf-8")
        written.append(path.name)

    # ASCII only: committed generated files are byte-compared by the drift guard.
    (GENERATED_TS / "version.ts").write_text(
        "// GENERATED by packages/contracts/scripts/gen.py -- do not edit.\n"
        f'export const PROTOCOL_VERSION = "{PROTOCOL_VERSION}";\n',
        encoding="utf-8",
    )

    print(f"schema: {', '.join(written)}")
    print(f"version.ts: PROTOCOL_VERSION={PROTOCOL_VERSION}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
