/**
 * @inbox/contracts — the wire types, generated from the Pydantic source of truth.
 *
 * Consumers (cockpit, executor) import from here. Everything re-exported below lives in
 * `src/generated/` and is regenerated by `pnpm run gen-contracts`; the drift guard fails
 * the build if a committed artifact is stale.
 */
export {
  actionCallSchema,
  actionResultSchema,
  envelopeSchema,
  observationSchema,
  PROTOCOL_VERSION,
  type ActionCall,
  type ActionResult,
  type Envelope,
  type Observation,
} from "./generated/index.js";
